### ISSUE TITLE
[Feature] User documentation

### ISSUE THREAD

**Issue by MathildeNS** [naturalsolutions/ecoSecrets#1]
Many users of the demo stopped at the creation of a project. Potentially because of the difficulty of using the tool for the first time. 
Indeed, it is necessary to create objects and to understand the functioning and structure of GeoCam to use it. 

This is why a short **user documentation** (which will be improved) **has been published** to help you understand how GeoCam works. It is available here: https://natural-solutions.gitlab.io/geonature/annotation/user/start/ 

We will also put a button in the header of the tool to access it easily from the tool itself.

**Comment by camillemonchicourt** [comment]
An simple tool don't require user documentation.
And when it is existing, user don't often read it.
So there may is another problem. A concept problem or ergonomic concept ?

**Comment by MathildeNS** [comment]
Effectivement, la piste d’un problème d’ergonomie n’est pas à écarter. Il est vrai que ce n’est pas la première chose à laquelle on a pensé puisque nous n’avions pas eu jusqu’à lors de retours clairs à ce sujet donc merci de soulever la question.
En effet, des infobulles sur les boutons et les concepts sont une excellente idée pour éclaircir l’utilisation de l’outil et simple à mettre en place.
De même, on peut en effet imaginer une modale qui présenterai ce schéma pour illustrer la structure de l’outil et les termes abordés.
En ce qui concerne la documentation, il est vrai que peu d’utilisateurs prennent le temps de la lire. Toutefois, celle-ci étant déjà réalisée autant la rendre accessible facilement aux personnes qui le souhaiteraient.
Merci pour tes retours c’est toujours un plaisir de pouvoir échanger et avoir l’avis d’autres personnes.

[english below]
Indeed, the possibility of a problem of ergonomics is to consider. It's true that it's not the first thing we thought because we didn't have any clear feedback on this subject until now, so thank you for raising the issue.
Indeed, tooltips on buttons and concepts are an excellent idea to clarify the use of the tool and simple to implement.
Similarly, we can indeed imagine a modal that would present this diagram to illustrate the structure of the tool and the terms covered.
Regarding the documentation, it is true that few users take the time to read it. However, since it is already done, it should be easily accessible to those who wish to do so.
Thank you for your feedback, it's always a pleasure to be able to exchange and have the opinion of other people.
