### ISSUE TITLE
[Feature] Gestion de 2 fichiers par observation pour gestion des données audio par geocam

### ISSUE THREAD

**Issue by schamaille** [naturalsolutions/ecoSecrets#4]
Idée: si Geocam pouvait gérer pour chaque 'observation' 2 fichiers, 1 fichier image + un autre d'un autre format, alors l'outil pourrait être utile pour la gestion et annotation de fichier audio: l'image affichée
serait celle du spectrogramme correspondant au fichier audio, le fichier audio lui-même étant
accessible par un bouton pour écoute/téléchargement etc. Le spectro pourrait d'ailleurs être créé 'in situ' par geocam au moment de l'upload d'un fichier reconnu comme un fichier audio, ou bien créé par ailleurs par l'utilisateur et chargé comme une image de piège photo.
L'avantage que je vois à cela c'est que toute la structure mise en place pour passer un modèle d'IA sur les images de pièges photo est alors réutilisable pour des modèles d'IA audio, la grande majorité étant basée sur les
images des spectros.

**Comment by camillemonchicourt** [comment]
Oui nous sommes aussi intéressés par la gestion et l'analyse des fichiers audio dans GeoCam.

Cependant je pense qu'il faut étudier leur fonctionnement et différences et pas uniquement pouvoir ajouter 2 fichiers par observation.
Si le fichier associé à une observation est un audio ou l'image d'un spectogramme, alors cela est bien différent dans sa gestion et son analyse.

Selon moi, il faut pouvoir associer un seul fichier principal d'observation et le typer, et ensuite pourquoi pas pouvoir lui associer des fichiers complémentaires d'infos.

Mais pour l'audio je privilégierai vraiment de charger uniquement le fichier audio source et que l'application génère un spectogramme de celui-ci pour bien avoir le fichier source et une gestion / traitement homogène des données audio.

**Comment by geobrun** [comment]
Même avis que @camillemonchicourt : un seul fichier et génération du spectrogramme côté serveur.
